[project]
name = "unit"
version = "0.1.0"
description = "Unit converter app using Streamlit"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.43.2",
    "pint>=0.24.4"
]
